### ISSUE TITLE
US1: Single MIT Success List App

### ISSUE THREAD

**Issue by 3dcantaloupe** [CSE-110-Winter-2024/project-team-24#31]
As a user I want an app that will allow me to easily enter and checkoff my MIT for the day so that I will be reminded of my MIT and more likely to get it done before the end of the day

- [x] #43 
- [x] #41 
- [x] #40 
- [x] #42 
- [x] #47 
- [x] #49

**Comment by pink10000** [comment]
this looks like it's finished
