### ISSUE TITLE
US8a: Schedule recurring weekly events from Today screen

### ISSUE THREAD

**Issue by MounirIssa** [CSE-110-Winter-2024/project-team-24#85]
As a user I want to be able to schedule weekly recurring goals from the Today screen so that I can conveniently make my new goal for today to effortlessly reappear on a weekly schedule

- [x] #97 
- [x] #98

**Comment by 3dcantaloupe** [comment]
As a user I want to be able to schedule weekly recurring goals from the Today screen so that I can conveniently make my new goal for today to effortlessly reappear on a weekly schedule

**Comment by pink10000** [comment]
@newracket is this the task to unify 8a and 8b?
