### ISSUE TITLE
US8b: Schedule daily, monthly, and yearly recurring events

### ISSUE THREAD

**Issue by MounirIssa** [CSE-110-Winter-2024/project-team-24#86]
As a user I want to be able to schedule a range of periodically recurring goals from the Today screen so that I can conveniently make my new goal for today to effortlessly reappear on a schedule

- [x] #98 
- [x] #101

**Comment by 3dcantaloupe** [comment]
As a user I want to be able to schedule a range of periodically recurring goals from the Today screen so that I can conveniently make my new goal for today to effortlessly reappear on a schedule
