### ISSUE TITLE
US9b: Delete a recurring goal

### ISSUE THREAD

**Issue by MounirIssa** [CSE-110-Winter-2024/project-team-24#89]
As a user I want to be able to delete a recurring event so that I'm not repeatedly reminded of something that isn't relevant anymore

- [x] #102 
- [x] #103 
- [x] #109 
- [x] #118

**Comment by 3dcantaloupe** [comment]
As a user I want to be able to delete a recurring event so that I'm not repeatedly reminded of something that isn't relevant anymore

**Comment by pink10000** [comment]
Delete a recurring event by holding the task.

**Comment by pink10000** [comment]
This is on branch [us9b-1] as of right now.
