### ISSUE TITLE
US10b: Treat Tomorrow goals like Today goals

### ISSUE THREAD

**Issue by MounirIssa** [CSE-110-Winter-2024/project-team-24#91]
As a user I want the same functionalities for Tomorrow goals as Today goals so that I can more easily track my goals and their completion

- [x] #102 
- [x] #103 
- [x] #106 
- [x] #110

**Comment by 3dcantaloupe** [comment]
As a user I want the same functionalities for Tomorrow goals as Today goals so that I can more easily track my goals and their completion
