### ISSUE TITLE
US11b: Additional pending goal actions

### ISSUE THREAD

**Issue by arnavdandu** [CSE-110-Winter-2024/project-team-24#96]
As a user I additionally want to be able to delete, finish, or move a pending goal to Tomorrow so that I can more easily manage my pending goals

- [x] #108 
- [x] #111 
- [x] #118

**Comment by 3dcantaloupe** [comment]
As a user I additionally want to be able to delete, finish, or move a pending goal to Tomorrow so that I can more easily manage my pending goals
