### ISSUE TITLE
US8a-1: User Interface for creating tasks

### ISSUE THREAD

**Issue by newracket** [CSE-110-Winter-2024/project-team-24#97]
When the plus button is clicked, the add task menu shows up.

LOOKS LIKE THIS:

![Image](https://github.com/CSE-110-Winter-2024/project-team-24/assets/5413412/e9fa3e79-bc74-4d0a-8768-1a22a0476790)

**Comment by pink10000** [comment]
why does it look ugly

**Comment by pink10000** [comment]
can we get our figma engineer to change it?

**Comment by newracket** [comment]
> can we get our figma engineer to change it?

ok @pink10000 fix it

**Comment by pink10000** [comment]
finished with it, see #100
